/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import internalframe.PanelDeControl;
import java.awt.BorderLayout;
import panel.ZonaDeDibujo;

/**
 * Ventana principal donde sucede toda la magia.
 * @author Fran
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final ZonaDeDibujo zonaDeDibujo;
    private final PanelDeControl panelDeControl;
    
    public VentanaPrincipal() {
        initComponents();
        setSize(1024,720);
        setExtendedState(MAXIMIZED_BOTH);
        zonaDeDibujo = new ZonaDeDibujo();
        panelDeControl = new PanelDeControl(zonaDeDibujo);
        add(zonaDeDibujo, BorderLayout.CENTER);
        add(panelDeControl, BorderLayout.EAST);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}