package internalframe;

import hilo.Pintor;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Point;
import javax.swing.JColorChooser;
import panel.ZonaDeDibujo;

/**
 * Clase encargada de llamar al primer pintor y darle los valores que el usuario pida como color, ramificaciones etc...
 * @author Fran
 */
public class PanelDeControl extends javax.swing.JInternalFrame {

    private final ZonaDeDibujo zonaDeDibujo;
    
    public PanelDeControl(ZonaDeDibujo zonaDeDibujo) {
        initComponents();
        this.zonaDeDibujo = zonaDeDibujo;
        setVisible(true);
    }
    private void dibujar() {
        Color colorInicial = consigueColorInicial();
        Color colorFinal = consigueColorFinal();        
        zonaDeDibujo.repaint();
        int ramificaciones = (int) (jSpinnerRamificaciones.getValue());
        int grosor = (int) (jSpinnerGrosor.getValue());
        int iteraciones = (int) (jSpinnerNivelesDeRama.getValue());
        float proporcion = (float) (jSpinnerProporcion.getValue());
        float  velocidad = (float)(jSpinnerVelocidad.getValue());
        
        int rojoInicial = colorInicial.getRed();
        int verdeInicial = colorInicial.getGreen();
        int azulInicial = colorInicial.getBlue();
        
        int incrementoRojo = (colorFinal.getRed() - colorInicial.getRed()) / iteraciones;
        int incrementoVerde = (colorFinal.getGreen() - colorInicial.getGreen()) / iteraciones;
        int incrementoAzul = (colorFinal.getBlue() - colorInicial.getBlue()) / iteraciones;
        
        Point pInicial = new Point(
                (int)(zonaDeDibujo.getWidth()/2),
                (int)(zonaDeDibujo.getHeight() - 50)
        );
        Point pFinal = new Point(
                (int)(pInicial.x + Math.cos(Math.toRadians(90))*75*proporcion ),
                (int)(pInicial.y - Math.sin(Math.toRadians(90))*75*proporcion)                            
        );

        Graphics2D brocha = (Graphics2D) (zonaDeDibujo.getGraphics());
        brocha.setColor(colorInicial);
        brocha.setStroke(new BasicStroke(grosor));
        
        new Pintor(90, pInicial, pFinal, ramificaciones, grosor,
                iteraciones, proporcion/2 + proporcion/4,
                velocidad, brocha, rojoInicial + incrementoRojo, incrementoRojo, verdeInicial + incrementoVerde,
                incrementoVerde, azulInicial + incrementoAzul, incrementoAzul).start();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerProporcion = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerRamificaciones = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerVelocidad = new javax.swing.JSpinner();
        jSpinnerNivelesDeRama = new javax.swing.JSpinner();
        autor = new javax.swing.JLabel();
        jButtonDibujar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerGrosor = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldColorInicial = new javax.swing.JTextField();
        jTextFieldColorFinal = new javax.swing.JTextField();

        jLabel1.setText("COLOR :");

        jLabel2.setText("NIVELES DE RAMA:");

        jSpinnerProporcion.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.1f), Float.valueOf(2.0f), Float.valueOf(0.1f)));

        jLabel3.setText("PROPORCIÓN :");

        jLabel4.setText("RAMIFICACIONES: ");

        jSpinnerRamificaciones.setModel(new javax.swing.SpinnerNumberModel(2, 2, 5, 1));

        jLabel5.setText("VELOCIDAD:");

        jSpinnerVelocidad.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.1f), Float.valueOf(10.0f), Float.valueOf(0.1f)));

        jSpinnerNivelesDeRama.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));

        autor.setText("PROGRAMA CREADO POR FRANCISCO ENRIQUE CORDOVA GONZALEZ");

        jButtonDibujar.setText("DIBUJAR");
        jButtonDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDibujarActionPerformed(evt);
            }
        });

        jLabel6.setText("GROSOR:");

        jSpinnerGrosor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));

        jLabel7.setText("a");

        jTextFieldColorInicial.setEditable(false);
        jTextFieldColorInicial.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldColorInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldColorInicialMouseClicked(evt);
            }
        });

        jTextFieldColorFinal.setEditable(false);
        jTextFieldColorFinal.setBackground(new java.awt.Color(255, 0, 51));
        jTextFieldColorFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldColorFinalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSpinnerProporcion)
                                .addComponent(jSpinnerRamificaciones)
                                .addComponent(jSpinnerVelocidad)
                                .addComponent(jSpinnerNivelesDeRama)
                                .addComponent(jSpinnerGrosor, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldColorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldColorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(autor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButtonDibujar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldColorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNivelesDeRama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerProporcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerRamificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinnerGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonDibujar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(autor)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDibujarActionPerformed
        dibujar();
    }//GEN-LAST:event_jButtonDibujarActionPerformed

    private void jTextFieldColorInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldColorInicialMouseClicked
        jTextFieldColorInicial.setBackground(JColorChooser.showDialog(null, "Elige un color", jTextFieldColorInicial.getBackground()));
    }//GEN-LAST:event_jTextFieldColorInicialMouseClicked

    private void jTextFieldColorFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldColorFinalMouseClicked
        jTextFieldColorFinal.setBackground(JColorChooser.showDialog(null, "Elige un color", jTextFieldColorFinal.getBackground()));
    }//GEN-LAST:event_jTextFieldColorFinalMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autor;
    private javax.swing.JButton jButtonDibujar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner jSpinnerGrosor;
    private javax.swing.JSpinner jSpinnerNivelesDeRama;
    private javax.swing.JSpinner jSpinnerProporcion;
    private javax.swing.JSpinner jSpinnerRamificaciones;
    private javax.swing.JSpinner jSpinnerVelocidad;
    private javax.swing.JTextField jTextFieldColorFinal;
    private javax.swing.JTextField jTextFieldColorInicial;
    // End of variables declaration//GEN-END:variables

    private Color consigueColorInicial() {        
        return jTextFieldColorInicial.getBackground();
    }

    private Color consigueColorFinal() {        
        return jTextFieldColorFinal.getBackground();      
    }
}